# These tests are disabled until Dragonfly works well with BullMQ.
name: bullmq-tests
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    timeout-minutes: 60
    container:
      image: ghcr.io/romange/alpine-dev:latest
      options: --security-opt seccomp=unconfined
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install NodeJs
        run: |
          apk add --no-cache nodejs npm yarn jq
          node --version
          npm --version
          yarn --version
          mkdir -p $GITHUB_WORKSPACE/build
      - name: Configure/Build
        run: |
          cd $GITHUB_WORKSPACE/build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -GNinja
          ninja dragonfly
          ./dragonfly --alsologtostderr --cluster_mode=emulated --lock_on_hashtags --dbfilename= &
      - name: Build BullMQ
        run: |
          DOWNLOAD_URL=$(curl -s https://api.github.com/repos/taskforcesh/bullmq/releases/latest | jq -r '.tarball_url')
          echo "Downloading latest BullMQ release from ${DOWNLOAD_URL}"
          wget -O bullmq.tar.gz ${DOWNLOAD_URL}
          tar -zxvf bullmq.tar.gz
          mv taskforcesh-bullmq-* bullmq
          cd bullmq
          pwd
          yarn install
          yarn build
      - name: Test BullMQ
        run: |
          cd $GITHUB_WORKSPACE/bullmq
          BULLMQ_TEST_PREFIX={b} yarn test
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: unit_logs
          path: /tmp/*INFO*
